package de.stustapay.stustapay.ui.root

import de.stustapay.stustapay.R
import de.stustapay.stustapay.model.Access


val startpageItems = listOf(
    StartpageItem(iconId = de.stustapay.libssp.R.drawable.shopping_cart_24,
        label = R.string.root_item_sale,
        navDestination = RootNavDests.sale,
        canAccess = { u, t -> Access.canSell(u, t) }),
    StartpageItem(iconId = de.stustapay.libssp.R.drawable.account_balance_wallet_24,
        label = R.string.root_item_topup,
        navDestination = RootNavDests.topup,
        canAccess = { u, t -> Access.canTopUp(t, u) }),
    StartpageItem(iconId = de.stustapay.libssp.R.drawable.local_activity_24,
        label = R.string.root_item_ticket,
        navDestination = RootNavDests.ticket,
        canAccess = { u, t -> Access.canSellTicket(t, u) }),
    StartpageItem(iconId = de.stustapay.libssp.R.drawable.favorite_24,
        label = R.string.root_item_rewards,
        navDestination = RootNavDests.rewards,
        canAccess = { u, _ -> Access.canGiveVouchers(u) || Access.canGiveFreeTickets(u) }),
    StartpageItem(iconId = de.stustapay.libssp.R.drawable.view_list_24,
        label = R.string.sale_history_title,
        navDestination = RootNavDests.history,
        canAccess = { u, t -> Access.canSell(u, t) }),
    StartpageItem(iconId = de.stustapay.libssp.R.drawable.info_24,
        label = R.string.customer_title,
        navDestination = RootNavDests.status,
        canAccess = { _, _ -> true }),
    StartpageItem(iconId = de.stustapay.libssp.R.drawable.refresh_24,
        label = R.string.customer_swap,
        navDestination = RootNavDests.swap,
        canAccess = { u, _, -> Access.canSwap(u) }),
    StartpageItem(iconId = de.stustapay.libssp.R.drawable.account_circle_24,
        label = R.string.management_title,
        navDestination = RootNavDests.cashier,
        canAccess = { u, t -> Access.canManageCashiers(u) or Access.canViewCashier(u) or Access.canPayOut(t, u) or Access.canTopUp(t, u) or Access.canSellTicket(t, u) }),
    StartpageItem(iconId = de.stustapay.libssp.R.drawable.money_bag_24,
        label = R.string.management_vault_title,
        navDestination = RootNavDests.vault,
        canAccess = { u, _ -> Access.canManageCashiers(u) }),
    StartpageItem(iconId = de.stustapay.libssp.R.drawable.date_range_24,
        label = R.string.root_item_stats,
        navDestination = RootNavDests.stats,
        canAccess = { u, _ -> Access.canViewStats(u) }),
)