/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.stustapay.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param name 
 * @param nodeId 
 * @param id 
 * @param currentCashierId 
 * @param currentTillId 
 * @param balance 
 * @param accountId 
 */
@Serializable

data class CashRegister (

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "node_id")
    val nodeId: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger,

    @SerialName(value = "id")
    val id: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger,

    @SerialName(value = "current_cashier_id")
    val currentCashierId: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger?,

    @SerialName(value = "current_till_id")
    val currentTillId: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger?,

    @Contextual @SerialName(value = "balance")
    val balance: kotlin.Double,

    @SerialName(value = "account_id")
    val accountId: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger

) {


}

