/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.stustapay.api.models

import de.stustapay.api.models.PaymentMethod
import de.stustapay.api.models.PendingLineItem
import de.stustapay.api.models.TicketScanResultEntry

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param uuid 
 * @param paymentMethod 
 * @param lineItems 
 * @param scannedTickets 
 * @param bookedAt 
 * @param customerAccountId 
 * @param cashierId 
 * @param tillId 
 * @param itemCount 
 * @param totalPrice 
 */
@Serializable

data class CompletedTicketSale (

    @Contextual @SerialName(value = "uuid")
    val uuid: java.util.UUID,

    @Contextual @SerialName(value = "payment_method")
    val paymentMethod: PaymentMethod,

    @SerialName(value = "line_items")
    val lineItems: kotlin.collections.List<PendingLineItem>,

    @SerialName(value = "scanned_tickets")
    val scannedTickets: kotlin.collections.List<TicketScanResultEntry>,

    @Contextual @SerialName(value = "booked_at")
    val bookedAt: java.time.OffsetDateTime,

    @SerialName(value = "customer_account_id")
    val customerAccountId: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger?,

    @SerialName(value = "cashier_id")
    val cashierId: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger,

    @SerialName(value = "till_id")
    val tillId: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger,

    @SerialName(value = "item_count")
    val itemCount: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger,

    @Contextual @SerialName(value = "total_price")
    val totalPrice: kotlin.Double

) {


}

