/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.stustapay.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param login 
 * @param displayName 
 * @param roleIds 
 * @param userTagPin 
 * @param userTagUid 
 * @param description 
 */
@Serializable

data class CreateUserPayload (

    @SerialName(value = "login")
    val login: kotlin.String,

    @SerialName(value = "display_name")
    val displayName: kotlin.String,

    @SerialName(value = "role_ids")
    val roleIds: kotlin.collections.List<@Contextual com.ionspin.kotlin.bignum.integer.BigInteger>,

    @SerialName(value = "user_tag_pin")
    val userTagPin: kotlin.String? = null,

    @SerialName(value = "user_tag_uid")
    val userTagUid: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger? = null,

    @SerialName(value = "description")
    val description: kotlin.String? = null

)

