/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.stustapay.api.models

import de.stustapay.api.models.EventPrivilege
import de.stustapay.api.models.NodePrivilege

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Describes a logged-in user in the system
 *
 * @param nodeId
 * @param id
 * @param login
 * @param displayName
 * @param activeRoleId
 * @param activeRoleName
 * @param eventPrivileges
 * @param nodePrivileges
 * @param description
 * @param userTagId
 * @param userTagUid
 * @param transportAccountId
 * @param cashRegisterId
 */
@Serializable

data class CurrentUser (

    @SerialName(value = "node_id")
    val nodeId: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger,

    @SerialName(value = "id")
    val id: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger,

    @SerialName(value = "login")
    val login: kotlin.String,

    @SerialName(value = "display_name")
    val displayName: kotlin.String,

    @SerialName(value = "active_role_id")
    val activeRoleId: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger? = null,

    @SerialName(value = "active_role_name")
    val activeRoleName: kotlin.String? = null,

    @SerialName(value = "event_privileges")
    val eventPrivileges: kotlin.collections.List<@Contextual EventPrivilege>? = null,

    @SerialName(value = "node_privileges")
    val nodePrivileges: kotlin.collections.List<@Contextual NodePrivilege>? = null,

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @SerialName(value = "user_tag_id")
    val userTagId: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger? = null,

    @SerialName(value = "user_tag_uid")
    val userTagUid: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger? = null,

    @SerialName(value = "transport_account_id")
    val transportAccountId: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger? = null,

    @SerialName(value = "cash_register_id")
    val cashRegisterId: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger? = null

) {


}
