/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.stustapay.api.models

import de.stustapay.api.models.EntryDirection

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param allowed 
 * @param reason 
 * @param direction 
 * @param areaId 
 * @param areaName 
 * @param groupId 
 * @param groupName 
 * @param isInside 
 * @param scannedAt 
 */
@Serializable

data class EntryScanResult (

    @SerialName(value = "allowed")
    val allowed: kotlin.Boolean,

    @SerialName(value = "reason")
    val reason: kotlin.String,

    @Contextual @SerialName(value = "direction")
    val direction: EntryDirection,

    @SerialName(value = "area_id")
    val areaId: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger?,

    @SerialName(value = "area_name")
    val areaName: kotlin.String?,

    @SerialName(value = "group_id")
    val groupId: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger?,

    @SerialName(value = "group_name")
    val groupName: kotlin.String?,

    @SerialName(value = "is_inside")
    val isInside: kotlin.Boolean?,

    @Contextual @SerialName(value = "scanned_at")
    val scannedAt: java.time.OffsetDateTime

) {


}

