/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.stustapay.api.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 *
 *
 * Values: customer_management,payout_management,create_user,cash_transport,terminal_login,supervised_terminal_login,grant_free_tickets,grant_vouchers
 */
@Serializable
enum class EventPrivilege(val value: kotlin.String) {

    @SerialName(value = "customer_management")
    customer_management("customer_management"),

    @SerialName(value = "payout_management")
    payout_management("payout_management"),

    @SerialName(value = "create_user")
    create_user("create_user"),

    @SerialName(value = "cash_transport")
    cash_transport("cash_transport"),

    @SerialName(value = "terminal_login")
    terminal_login("terminal_login"),

    @SerialName(value = "supervised_terminal_login")
    supervised_terminal_login("supervised_terminal_login"),

    @SerialName(value = "grant_free_tickets")
    grant_free_tickets("grant_free_tickets"),

    @SerialName(value = "grant_vouchers")
    grant_vouchers("grant_vouchers");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is EventPrivilege) "$data" else null

        /**
         * Returns a valid [EventPrivilege] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): EventPrivilege? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}
