/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.stustapay.api.models

import de.stustapay.api.models.UserTag

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param userTag 
 * @param userRoleId 
 */
@Serializable

data class LoginPayload (

    @SerialName(value = "user_tag")
    val userTag: UserTag,

    @SerialName(value = "user_role_id")
    val userRoleId: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger

) {


}

