/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.stustapay.api.models

import de.stustapay.api.models.Button

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param uuid 
 * @param customerTagUid 
 * @param buttons 
 * @param usedVouchers 
 */
@Serializable

data class NewSale (

    @Contextual @SerialName(value = "uuid")
    val uuid: java.util.UUID,

    @SerialName(value = "customer_tag_uid")
    val customerTagUid: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger,

    @SerialName(value = "buttons")
    val buttons: kotlin.collections.List<Button>,

    @SerialName(value = "used_vouchers")
    val usedVouchers: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger? = null

)

