/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.stustapay.api.models

import de.stustapay.api.models.PaymentMethod

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param uuid 
 * @param customerTagUids 
 * @param paymentMethod 
 */
@Serializable

data class NewTicketSale (

    @Contextual @SerialName(value = "uuid")
    val uuid: java.util.UUID,

    @SerialName(value = "customer_tag_uids")
    val customerTagUids: kotlin.collections.List<@Contextual com.ionspin.kotlin.bignum.integer.BigInteger>,

    @Contextual @SerialName(value = "payment_method")
    val paymentMethod: PaymentMethod?

)

