/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.stustapay.api.models

import de.stustapay.api.models.PaymentMethod
import de.stustapay.api.models.UserTagScan

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param uuid 
 * @param customerTags 
 * @param paymentMethod 
 */
@Serializable

data class NewTicketSale (

    @Contextual @SerialName(value = "uuid")
    val uuid: java.util.UUID,

    @SerialName(value = "customer_tags")
    val customerTags: kotlin.collections.List<UserTagScan>,

    @Contextual @SerialName(value = "payment_method")
    val paymentMethod: PaymentMethod?

) {


}

