/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.stustapay.api.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * Values: cash,sumup,tag,sumupOnline
 */
@Serializable
enum class PaymentMethod(val value: kotlin.String) {

    @SerialName(value = "cash")
    cash("cash"),

    @SerialName(value = "sumup")
    sumup("sumup"),

    @SerialName(value = "tag")
    tag("tag"),

    @SerialName(value = "sumup_online")
    sumupOnline("sumup_online");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is PaymentMethod) "$data" else null

        /**
         * Returns a valid [PaymentMethod] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): PaymentMethod? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

