/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.stustapay.api.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * Values: discount,topup,payout,money_transfer,imbalance,user_defined,ticket
 */
@Serializable
enum class ProductType(val value: kotlin.String) {

    @SerialName(value = "discount")
    discount("discount"),

    @SerialName(value = "topup")
    topup("topup"),

    @SerialName(value = "payout")
    payout("payout"),

    @SerialName(value = "money_transfer")
    money_transfer("money_transfer"),

    @SerialName(value = "imbalance")
    imbalance("imbalance"),

    @SerialName(value = "user_defined")
    user_defined("user_defined"),

    @SerialName(value = "ticket")
    ticket("ticket");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ProductType) "$data" else null

        /**
         * Returns a valid [ProductType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ProductType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

