/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.stustapay.api.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 *
 *
 * Values: regular_vat,reduced_vat,no_tax,transparent
 */
@Serializable
enum class TaxType(val value: kotlin.String) {

    @SerialName(value = "regular_vat")
    regular_vat("regular_vat"),

    @SerialName(value = "reduced_vat")
    reduced_vat("reduced_vat"),

    @SerialName(value = "no_tax")
    no_tax("no_tax"),

    @SerialName(value = "transparent")
    transparent("transparent");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is TaxType) "$data" else null

        /**
         * Returns a valid [TaxType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): TaxType? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}
