/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.stustapay.api.models

import de.stustapay.api.models.EventPrivilege
import de.stustapay.api.models.NodePrivilege
import de.stustapay.api.models.TerminalTillConfig
import de.stustapay.api.models.TerminalUserTagSecrets
import de.stustapay.api.models.UserRole

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param id
 * @param name
 * @param description
 * @param eventName
 * @param activeUserId
 * @param availableRoles
 * @param userEventPrivileges
 * @param userNodePrivileges
 * @param secrets
 * @param till
 * @param testMode
 * @param testModeMessage
 */
@Serializable

data class TerminalConfig (

    @SerialName(value = "id")
    val id: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "description")
    val description: kotlin.String?,

    @SerialName(value = "event_name")
    val eventName: kotlin.String,

    @SerialName(value = "active_user_id")
    val activeUserId: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger?,

    @SerialName(value = "available_roles")
    val availableRoles: kotlin.collections.List<UserRole>,

    @SerialName(value = "user_event_privileges")
    val userEventPrivileges: kotlin.collections.List<@Contextual EventPrivilege>?,

    @SerialName(value = "user_node_privileges")
    val userNodePrivileges: kotlin.collections.List<@Contextual NodePrivilege>?,

    @SerialName(value = "secrets")
    val secrets: TerminalUserTagSecrets?,

    @SerialName(value = "till")
    val till: TerminalTillConfig?,

    @SerialName(value = "test_mode")
    val testMode: kotlin.Boolean,

    @SerialName(value = "test_mode_message")
    val testModeMessage: kotlin.String

) {


}
