/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.stustapay.api.models

import de.stustapay.api.models.Privilege
import de.stustapay.api.models.TerminalTillConfig
import de.stustapay.api.models.TerminalUserTagSecrets
import de.stustapay.api.models.UserRole

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param name 
 * @param description 
 * @param eventName 
 * @param activeUserId 
 * @param availableRoles 
 * @param userPrivileges 
 * @param secrets 
 * @param till 
 * @param testMode 
 * @param testModeMessage 
 */
@Serializable

data class TerminalConfig (

    @SerialName(value = "id")
    val id: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "description")
    val description: kotlin.String?,

    @SerialName(value = "event_name")
    val eventName: kotlin.String,

    @SerialName(value = "active_user_id")
    val activeUserId: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger?,

    @SerialName(value = "available_roles")
    val availableRoles: kotlin.collections.List<UserRole>,

    @SerialName(value = "user_privileges")
    val userPrivileges: kotlin.collections.List<@Contextual Privilege>?,

    @SerialName(value = "secrets")
    val secrets: TerminalUserTagSecrets?,

    @SerialName(value = "till")
    val till: TerminalTillConfig?,

    @SerialName(value = "test_mode")
    val testMode: kotlin.Boolean,

    @SerialName(value = "test_mode_message")
    val testModeMessage: kotlin.String

) {


}

