/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.stustapay.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param name
 * @param price
 * @param taxRateId
 * @param userTagVariantIds
 * @param isLocked
 * @param initialTopUpAmount
 * @param nodeId
 * @param id
 * @param taxName
 * @param taxRate
 * @param totalPrice
 */
@Serializable

data class Ticket (

    @SerialName(value = "name")
    val name: kotlin.String,

    @Contextual @SerialName(value = "price")
    val price: kotlin.Double,

    @SerialName(value = "tax_rate_id")
    val taxRateId: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger,

    @SerialName(value = "user_tag_variant_ids")
    val userTagVariantIds: kotlin.collections.List<@Contextual com.ionspin.kotlin.bignum.integer.BigInteger>,

    @SerialName(value = "is_locked")
    val isLocked: kotlin.Boolean,

    @Contextual @SerialName(value = "initial_top_up_amount")
    val initialTopUpAmount: kotlin.Double,

    @SerialName(value = "node_id")
    val nodeId: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger,

    @SerialName(value = "id")
    val id: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger,

    @SerialName(value = "tax_name")
    val taxName: kotlin.String,

    @Contextual @SerialName(value = "tax_rate")
    val taxRate: kotlin.Double,

    @Contextual @SerialName(value = "total_price")
    val totalPrice: kotlin.Double

) {


}
