/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.stustapay.api.models

import de.stustapay.api.models.Account
import de.stustapay.api.models.Ticket
import de.stustapay.api.models.TicketVoucher

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param customerTagUid 
 * @param customerTagPin 
 * @param ticket 
 * @param totalPrice 
 * @param topUpAmount 
 * @param ticketVoucher 
 * @param account 
 */
@Serializable

data class TicketScanResultEntry (

    @SerialName(value = "customer_tag_uid")
    val customerTagUid: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger,

    @SerialName(value = "customer_tag_pin")
    val customerTagPin: kotlin.String,

    @SerialName(value = "ticket")
    val ticket: Ticket,

    @Contextual @SerialName(value = "total_price")
    val totalPrice: kotlin.Double,

    @Contextual @SerialName(value = "top_up_amount")
    val topUpAmount: kotlin.Double? = 0.0,

    @SerialName(value = "ticket_voucher")
    val ticketVoucher: TicketVoucher? = null,

    @SerialName(value = "account")
    val account: Account? = null

) {


}

