/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.stustapay.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param key0 
 * @param key1 
 */
@Serializable

data class UserTagSecret (

    @SerialName(value = "key0")
    val key0: kotlin.String,

    @SerialName(value = "key1")
    val key1: kotlin.String

) {


}

