/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.stustapay.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * a scanned tag before ticket sale
 *
 * @param tagUid 
 * @param tagPin 
 * @param topUpAmount 
 * @param voucherToken 
 */
@Serializable

data class UserTagScan (

    @SerialName(value = "tag_uid")
    val tagUid: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger,

    @SerialName(value = "tag_pin")
    val tagPin: kotlin.String,

    @Contextual @SerialName(value = "top_up_amount")
    val topUpAmount: kotlin.Double? = 0.0,

    @SerialName(value = "voucher_token")
    val voucherToken: kotlin.String? = null

) {


}

