/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.stustapay.api.models

import de.stustapay.api.models.EventPrivilege
import de.stustapay.api.models.NodePrivilege

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 *
 *
 * @param name
 * @param eventPrivileges
 * @param nodePrivileges
 * @param id
 * @param nodeId
 * @param canAssignAllRoles
 * @param assignableRoleIds
 */
@Serializable

data class UserRole (

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "event_privileges")
    val eventPrivileges: kotlin.collections.List<@Contextual EventPrivilege>,

    @SerialName(value = "node_privileges")
    val nodePrivileges: kotlin.collections.List<@Contextual NodePrivilege>,

    @SerialName(value = "id")
    val id: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger,

    @SerialName(value = "node_id")
    val nodeId: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger,

    @SerialName(value = "can_assign_all_roles")
    val canAssignAllRoles: kotlin.Boolean? = false,

    @SerialName(value = "assignable_role_ids")
    val assignableRoleIds: kotlin.collections.List<@Contextual com.ionspin.kotlin.bignum.integer.BigInteger>? = null

) {


}
