/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.stustapay.api.models

import de.stustapay.api.models.Privilege

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param name 
 * @param isPrivileged 
 * @param privileges 
 * @param nodeId 
 * @param nodeName 
 * @param isAtCurrentNode 
 */
@Serializable

data class UserRoleInfo (

    @SerialName(value = "id")
    val id: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "is_privileged")
    val isPrivileged: kotlin.Boolean,

    @SerialName(value = "privileges")
    val privileges: kotlin.collections.List<@Contextual Privilege>,

    @SerialName(value = "node_id")
    val nodeId: @Contextual com.ionspin.kotlin.bignum.integer.BigInteger,

    @SerialName(value = "node_name")
    val nodeName: kotlin.String,

    @SerialName(value = "is_at_current_node")
    val isAtCurrentNode: kotlin.Boolean

)

