"""
errorcodes from the manual
"""

errors = {
    1: "JSON_CODE_COMMAND_UNKNOWN",
    2: "JSON_CODE_COMMAND_UNSUPPORTED",
    3: "JSON_CODE_PARAMETER_MISSING",
    4: "JSON_CODE_PARAMETER_INVALID",
    9: "JSON_CODE_PARAMETER_INVALID_BASE64",
    27: "JSON_CODE_ERROR_PARAMETER_PASSWORD_INVALID",
    28: "JSON_CODE_ERROR_PARAMETER_PUK_INVALID",
    29: "JSON_CODE_ERROR_PARAMETER_USER_WRONG",
    30: "JSON_CODE_ERROR_PARAMETER_PASSWORD_WRONG",
    31: "JSON_CODE_ERROR_PARAMETER_PUK_WRONG",
    32: "JSON_CODE_ERROR_PARAMETER_USER_BLOCKED",
    33: "JSON_CODE_ERROR_PARAMETER_PUK_BLOCKED --- now you are fucked!",
    34: "JSON_CODE_ERROR_PARAMETER_PASSWORD_SAME",
    5017: "ERROR_NO_ORDER",
}


def dnerror(code):
    return {"Status": "error", "Code": code, "Desc": errors[code]}
