import {
  AccountRoutes,
  CashRegistersRoutes,
  CustomerRoutes,
  EntryAreaRoutes,
  EntryGroupRoutes,
  EntryLogRoutes,
  MdmRoutes,
  PayoutRunRoutes,
  ProductRoutes,
  SumUpTransactionRoutes,
  TaxRateRoutes,
  TerminalRoutes,
  TicketRoutes,
  TillLayoutRoutes,
  TillProfileRoutes,
  TillRoutes,
  TseRoutes,
  UserRoutes,
  UserRoleRoutes,
  UserTagRoutes,
  UserToRoleRoutes,
} from "@/app/routes";

export const helpLinkTargets = {
  profile: "/profile",
  nodeOverview: (nodeId: number) => `/node/${nodeId}`,
  nodeSettings: (nodeId: number) => `/node/${nodeId}/settings`,
  nodeStats: (nodeId: number) => `/node/${nodeId}/stats`,
  users: (nodeId: number) => UserRoutes.list(nodeId),
  userRoles: (nodeId: number) => UserRoleRoutes.list(nodeId),
  userAssignments: (nodeId: number) => UserToRoleRoutes.list(nodeId),
  products: (nodeId: number) => ProductRoutes.list(nodeId),
  tickets: (nodeId: number) => TicketRoutes.list(nodeId),
  taxRates: (nodeId: number) => TaxRateRoutes.list(nodeId),
  customers: (nodeId: number) => CustomerRoutes.list(nodeId),
  accounts: (nodeId: number) => AccountRoutes.list(nodeId),
  userTags: (nodeId: number) => UserTagRoutes.list(nodeId),
  terminals: (nodeId: number) => TerminalRoutes.list(nodeId),
  tills: (nodeId: number) => TillRoutes.list(nodeId),
  tillProfiles: (nodeId: number) => TillProfileRoutes.list(nodeId),
  tillLayouts: (nodeId: number) => TillLayoutRoutes.list(nodeId),
  cashRegisters: (nodeId: number) => CashRegistersRoutes.list(nodeId),
  payouts: (nodeId: number) => PayoutRunRoutes.list(nodeId),
  entryAreas: (nodeId: number) => EntryAreaRoutes.list(nodeId),
  entryGroups: (nodeId: number) => EntryGroupRoutes.list(nodeId),
  entryLogs: (nodeId: number) => EntryLogRoutes.list(nodeId),
  tses: (nodeId: number) => TseRoutes.list(nodeId),
  sumup: (nodeId: number) => SumUpTransactionRoutes.list(nodeId),
  mdm: (nodeId: number) => MdmRoutes.list(nodeId),
  dsfinvk: (nodeId: number) => `/node/${nodeId}/dsfinvk`,
} as const;
