database:
  host: localhost
  user: stustapay
  password: stustapay
  dbname: "stustapay"
  port: 5433

core:
  test_mode: true
  test_mode_message: "using test instance"
  secret_key: "dummy secret key"
  sumup_enabled: true

administration:
  base_url: "http://localhost:8081"
  host: "localhost"
  port: 8081

customerportal:
  base_url: "http://localhost:8082"
  host: "localhost"
  port: 8082

terminalserver:
  base_url: "http://localhost:8083"
  host: "localhost"
  port: 8083

headwind:
  enabled: false
  base_url: "http://localhost:8080/headwind"
  login: "admin"
  password_md5: "replace-with-md5-hash"
