/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.stustapay.api.models

import de.stustapay.api.models.AccountType
import de.stustapay.api.models.ProductRestriction
import de.stustapay.api.models.UserTagHistoryEntry

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param nodeId 
 * @param id 
 * @param type 
 * @param name 
 * @param comment 
 * @param balance 
 * @param vouchers 
 * @param userTagUid 
 * @param restriction 
 * @param tagHistory 
 * @param userTagUidHex 
 * @param userTagComment 
 */
@Serializable

data class Account (

    @SerialName(value = "node_id")
    val nodeId: kotlin.Int,

    @SerialName(value = "id")
    val id: kotlin.Int,

    @Contextual @SerialName(value = "type")
    val type: AccountType,

    @SerialName(value = "name")
    val name: kotlin.String?,

    @SerialName(value = "comment")
    val comment: kotlin.String?,

    @Contextual @SerialName(value = "balance")
    val balance: java.math.BigDecimal,

    @SerialName(value = "vouchers")
    val vouchers: kotlin.Int,

    @SerialName(value = "user_tag_uid")
    val userTagUid: kotlin.Int?,

    @Contextual @SerialName(value = "restriction")
    val restriction: ProductRestriction?,

    @SerialName(value = "tag_history")
    val tagHistory: kotlin.collections.List<UserTagHistoryEntry>,

    @SerialName(value = "user_tag_uid_hex")
    val userTagUidHex: kotlin.String?,

    @SerialName(value = "user_tag_comment")
    val userTagComment: kotlin.String? = null

)

