/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.stustapay.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param tillButtonId 
 * @param quantity 
 * @param price 
 */
@Serializable

data class Button (

    @SerialName(value = "till_button_id")
    val tillButtonId: kotlin.Int,

    @SerialName(value = "quantity")
    val quantity: kotlin.Int? = null,

    @Contextual @SerialName(value = "price")
    val price: java.math.BigDecimal? = null

)

