/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.stustapay.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param name 
 * @param nodeId 
 * @param id 
 * @param currentCashierId 
 * @param currentCashierTagUid 
 * @param currentTillId 
 * @param currentBalance 
 */
@Serializable

data class CashRegister (

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "node_id")
    val nodeId: kotlin.Int,

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "current_cashier_id")
    val currentCashierId: kotlin.Int?,

    @SerialName(value = "current_cashier_tag_uid")
    val currentCashierTagUid: kotlin.Int?,

    @SerialName(value = "current_till_id")
    val currentTillId: kotlin.Int?,

    @Contextual @SerialName(value = "current_balance")
    val currentBalance: java.math.BigDecimal

)

