/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.stustapay.api.models

import de.stustapay.api.models.UserRole
import de.stustapay.api.models.UserTag

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param userTag 
 * @param roles 
 */
@Serializable

data class CheckLoginResult (

    @SerialName(value = "user_tag")
    val userTag: UserTag,

    @SerialName(value = "roles")
    val roles: kotlin.collections.List<UserRole>

)

