/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.stustapay.api.models

import de.stustapay.api.models.PaymentMethod

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param paymentMethod 
 * @param customerTagUid 
 * @param customerAccountId 
 * @param amount 
 * @param oldBalance 
 * @param newBalance 
 * @param uuid 
 * @param bookedAt 
 * @param cashierId 
 * @param tillId 
 */
@Serializable

data class CompletedTopUp (

    @Contextual @SerialName(value = "payment_method")
    val paymentMethod: PaymentMethod,

    @SerialName(value = "customer_tag_uid")
    val customerTagUid: kotlin.Int,

    @SerialName(value = "customer_account_id")
    val customerAccountId: kotlin.Int,

    @Contextual @SerialName(value = "amount")
    val amount: java.math.BigDecimal,

    @Contextual @SerialName(value = "old_balance")
    val oldBalance: java.math.BigDecimal,

    @Contextual @SerialName(value = "new_balance")
    val newBalance: java.math.BigDecimal,

    @Contextual @SerialName(value = "uuid")
    val uuid: java.util.UUID,

    @Contextual @SerialName(value = "booked_at")
    val bookedAt: java.time.OffsetDateTime,

    @SerialName(value = "cashier_id")
    val cashierId: kotlin.Int,

    @SerialName(value = "till_id")
    val tillId: kotlin.Int

)

