/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.stustapay.api.models

import de.stustapay.api.models.Privilege

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Describes a logged-in user in the system
 *
 * @param nodeId 
 * @param id 
 * @param login 
 * @param displayName 
 * @param privileges 
 * @param userTagUidHex 
 * @param activeRoleId 
 * @param activeRoleName 
 * @param description 
 * @param userTagUid 
 * @param transportAccountId 
 * @param cashierAccountId 
 * @param cashRegisterId 
 */
@Serializable

data class CurrentUser (

    @SerialName(value = "node_id")
    val nodeId: kotlin.Int,

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "login")
    val login: kotlin.String,

    @SerialName(value = "display_name")
    val displayName: kotlin.String,

    @SerialName(value = "privileges")
    val privileges: kotlin.collections.List<@Contextual Privilege>,

    @SerialName(value = "user_tag_uid_hex")
    val userTagUidHex: kotlin.String?,

    @SerialName(value = "active_role_id")
    val activeRoleId: kotlin.Int? = null,

    @SerialName(value = "active_role_name")
    val activeRoleName: kotlin.String? = null,

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @SerialName(value = "user_tag_uid")
    val userTagUid: kotlin.ULong? = null,

    @SerialName(value = "transport_account_id")
    val transportAccountId: kotlin.Int? = null,

    @SerialName(value = "cashier_account_id")
    val cashierAccountId: kotlin.Int? = null,

    @SerialName(value = "cash_register_id")
    val cashRegisterId: kotlin.Int? = null

)

