/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.stustapay.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param login 
 * @param displayName 
 * @param roleNames 
 * @param userTagUid 
 * @param description 
 */
@Serializable

data class NewUser (

    @SerialName(value = "login")
    val login: kotlin.String,

    @SerialName(value = "display_name")
    val displayName: kotlin.String,

    @SerialName(value = "role_names")
    val roleNames: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "user_tag_uid")
    val userTagUid: kotlin.Int? = null,

    @SerialName(value = "description")
    val description: kotlin.String? = null

)

