/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.stustapay.api.models

import de.stustapay.api.models.LineItem
import de.stustapay.api.models.OrderType
import de.stustapay.api.models.PaymentMethod

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * represents a completely finished order with all relevant data
 *
 * @param id 
 * @param uuid 
 * @param totalPrice 
 * @param totalTax 
 * @param totalNoTax 
 * @param cancelsOrder 
 * @param bookedAt 
 * @param paymentMethod 
 * @param orderType 
 * @param cashierId 
 * @param tillId 
 * @param customerAccountId 
 * @param customerTagUid 
 * @param lineItems 
 * @param customerTagUidHex 
 */
@Serializable

data class Order (

    @SerialName(value = "id")
    val id: kotlin.Int,

    @Contextual @SerialName(value = "uuid")
    val uuid: java.util.UUID,

    @Contextual @SerialName(value = "total_price")
    val totalPrice: java.math.BigDecimal,

    @Contextual @SerialName(value = "total_tax")
    val totalTax: java.math.BigDecimal,

    @Contextual @SerialName(value = "total_no_tax")
    val totalNoTax: java.math.BigDecimal,

    @SerialName(value = "cancels_order")
    val cancelsOrder: kotlin.Int?,

    @Contextual @SerialName(value = "booked_at")
    val bookedAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "payment_method")
    val paymentMethod: PaymentMethod,

    @Contextual @SerialName(value = "order_type")
    val orderType: OrderType,

    @SerialName(value = "cashier_id")
    val cashierId: kotlin.Int?,

    @SerialName(value = "till_id")
    val tillId: kotlin.Int?,

    @SerialName(value = "customer_account_id")
    val customerAccountId: kotlin.Int?,

    @SerialName(value = "customer_tag_uid")
    val customerTagUid: kotlin.Int?,

    @SerialName(value = "line_items")
    val lineItems: kotlin.collections.List<LineItem>,

    @SerialName(value = "customer_tag_uid_hex")
    val customerTagUidHex: kotlin.String?

)

