/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.stustapay.api.models

import de.stustapay.api.models.PaymentMethod
import de.stustapay.api.models.PendingLineItem
import de.stustapay.api.models.TicketScanResultEntry

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param uuid 
 * @param paymentMethod 
 * @param lineItems 
 * @param scannedTickets 
 * @param itemCount 
 * @param totalPrice 
 */
@Serializable

data class PendingTicketSale (

    @Contextual @SerialName(value = "uuid")
    val uuid: java.util.UUID,

    @Contextual @SerialName(value = "payment_method")
    val paymentMethod: PaymentMethod?,

    @SerialName(value = "line_items")
    val lineItems: kotlin.collections.List<PendingLineItem>,

    @SerialName(value = "scanned_tickets")
    val scannedTickets: kotlin.collections.List<TicketScanResultEntry>,

    @SerialName(value = "item_count")
    val itemCount: kotlin.Int,

    @Contextual @SerialName(value = "total_price")
    val totalPrice: kotlin.Double

)

