/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.stustapay.api.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * Values: nodeAdministration,userManagement,cashTransport,terminalLogin,supervisedTerminalLogin,canBookOrders,grantFreeTickets,grantVouchers
 */
@Serializable
enum class Privilege(val value: kotlin.String) {

    @SerialName(value = "node_administration")
    nodeAdministration("node_administration"),

    @SerialName(value = "user_management")
    userManagement("user_management"),

    @SerialName(value = "cash_transport")
    cashTransport("cash_transport"),

    @SerialName(value = "terminal_login")
    terminalLogin("terminal_login"),

    @SerialName(value = "supervised_terminal_login")
    supervisedTerminalLogin("supervised_terminal_login"),

    @SerialName(value = "can_book_orders")
    canBookOrders("can_book_orders"),

    @SerialName(value = "grant_free_tickets")
    grantFreeTickets("grant_free_tickets"),

    @SerialName(value = "grant_vouchers")
    grantVouchers("grant_vouchers");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is Privilege) "$data" else null

        /**
         * Returns a valid [Privilege] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): Privilege? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

