/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.stustapay.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param cashierTagUid 
 * @param cashRegisterId 
 * @param registerStockingId 
 */
@Serializable

data class RegisterStockUpPayload (

    @SerialName(value = "cashier_tag_uid")
    val cashierTagUid: kotlin.Int,

    @SerialName(value = "cash_register_id")
    val cashRegisterId: kotlin.Int,

    @SerialName(value = "register_stocking_id")
    val registerStockingId: kotlin.Int

)

