/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.stustapay.api.models


import de.stustapay.api.models.TerminalSecrets
import de.stustapay.api.models.UserRole

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param name 
 * @param description 
 * @param profileName 
 * @param userPrivileges 
 * @param cashRegisterId 
 * @param cashRegisterName 
 * @param allowTopUp 
 * @param allowCashOut 
 * @param allowTicketSale 
 * @param buttons 
 * @param secrets 
 * @param activeUserId 
 * @param availableRoles 
 */
@Serializable

data class TerminalTillConfig (

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "description")
    val description: kotlin.String?,

    @SerialName(value = "profile_name")
    val profileName: kotlin.String,

    @SerialName(value = "user_privileges")
    val userPrivileges: kotlin.collections.List<Privilege>?,

    @SerialName(value = "cash_register_id")
    val cashRegisterId: kotlin.Int?,

    @SerialName(value = "cash_register_name")
    val cashRegisterName: kotlin.String?,

    @SerialName(value = "allow_top_up")
    val allowTopUp: kotlin.Boolean,

    @SerialName(value = "allow_cash_out")
    val allowCashOut: kotlin.Boolean,

    @SerialName(value = "allow_ticket_sale")
    val allowTicketSale: kotlin.Boolean,

    @SerialName(value = "buttons")
    val buttons: kotlin.collections.List<TerminalButton>?,

    @SerialName(value = "secrets")
    val secrets: TerminalSecrets?,

    @SerialName(value = "active_user_id")
    val activeUserId: kotlin.Int?,

    @SerialName(value = "available_roles")
    val availableRoles: kotlin.collections.List<UserRole>

)

