/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.stustapay.api.models

import de.stustapay.api.models.ProductRestriction

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param name 
 * @param price 
 * @param taxRateId 
 * @param restrictions 
 * @param isLocked 
 * @param initialTopUpAmount 
 * @param nodeId 
 * @param id 
 * @param taxName 
 * @param taxRate 
 * @param totalPrice 
 */
@Serializable

data class Ticket (

    @SerialName(value = "name")
    val name: kotlin.String,

    @Contextual @SerialName(value = "price")
    val price: java.math.BigDecimal,

    @SerialName(value = "tax_rate_id")
    val taxRateId: kotlin.Int,

    @SerialName(value = "restrictions")
    val restrictions: kotlin.collections.List<@Contextual ProductRestriction>,

    @SerialName(value = "is_locked")
    val isLocked: kotlin.Boolean,

    @Contextual @SerialName(value = "initial_top_up_amount")
    val initialTopUpAmount: java.math.BigDecimal,

    @SerialName(value = "node_id")
    val nodeId: kotlin.Int,

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "tax_name")
    val taxName: kotlin.String,

    @Contextual @SerialName(value = "tax_rate")
    val taxRate: java.math.BigDecimal,

    @Contextual @SerialName(value = "total_price")
    val totalPrice: java.math.BigDecimal

)

