/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.stustapay.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param name 
 * @param activeProfileId 
 * @param nodeId 
 * @param id 
 * @param zNr 
 * @param description 
 * @param activeShift 
 * @param sessionUuid 
 * @param registrationUuid 
 * @param activeUserId 
 * @param activeUserRoleId 
 * @param currentCashRegisterName 
 * @param currentCashRegisterBalance 
 * @param tseId 
 * @param tseSerial 
 */
@Serializable

data class Till (

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "active_profile_id")
    val activeProfileId: kotlin.Int,

    @SerialName(value = "node_id")
    val nodeId: kotlin.Int,

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "z_nr")
    val zNr: kotlin.Int,

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @SerialName(value = "active_shift")
    val activeShift: kotlin.String? = null,

    @Contextual @SerialName(value = "session_uuid")
    val sessionUuid: java.util.UUID? = null,

    @Contextual @SerialName(value = "registration_uuid")
    val registrationUuid: java.util.UUID? = null,

    @SerialName(value = "active_user_id")
    val activeUserId: kotlin.Int? = null,

    @SerialName(value = "active_user_role_id")
    val activeUserRoleId: kotlin.Int? = null,

    @SerialName(value = "current_cash_register_name")
    val currentCashRegisterName: kotlin.String? = null,

    @Contextual @SerialName(value = "current_cash_register_balance")
    val currentCashRegisterBalance: java.math.BigDecimal? = null,

    @SerialName(value = "tse_id")
    val tseId: kotlin.Int? = null,

    @SerialName(value = "tse_serial")
    val tseSerial: kotlin.String? = null

)

