/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.stustapay.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param sourceCashierTagUid 
 * @param targetCashierTagUid 
 */
@Serializable

data class TransferCashRegisterPayload (

    @SerialName(value = "source_cashier_tag_uid")
    val sourceCashierTagUid: kotlin.Int,

    @SerialName(value = "target_cashier_tag_uid")
    val targetCashierTagUid: kotlin.Int

)

