/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.stustapay.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param userTagUid 
 * @param roleNames 
 */
@Serializable

data class UpdateUserPayload (

    @SerialName(value = "user_tag_uid")
    val userTagUid: kotlin.Int,

    @SerialName(value = "role_names")
    val roleNames: kotlin.collections.List<kotlin.String>

)

