/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.stustapay.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param login 
 * @param displayName 
 * @param nodeId 
 * @param id 
 * @param userTagUidHex 
 * @param userTagUid 
 * @param description 
 * @param transportAccountId 
 * @param cashierAccountId 
 */
@Serializable

data class User (

    @SerialName(value = "login")
    val login: kotlin.String,

    @SerialName(value = "display_name")
    val displayName: kotlin.String,

    @SerialName(value = "node_id")
    val nodeId: kotlin.Int,

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "user_tag_uid_hex")
    val userTagUidHex: kotlin.String?,

    @SerialName(value = "user_tag_uid")
    val userTagUid: kotlin.ULong? = null,

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @SerialName(value = "transport_account_id")
    val transportAccountId: kotlin.Int? = null,

    @SerialName(value = "cashier_account_id")
    val cashierAccountId: kotlin.Int? = null

)

