-- revision: c66cbafc
-- requires: 2a15b453

alter table payout_run drop column execution_date;


do
$$
    begin
        create type tse_type as enum ('diebold_nixdorf');
    exception
        when duplicate_object then null;
    end
$$;

alter table tse
    add column ws_url text not null default '';
alter table tse
    add column ws_timeout double precision default 5;
alter table tse
    add column password text not null default '';
alter table tse
    add column type tse_type not null default 'diebold_nixdorf';
alter table tse
    rename column tse_id to id;
alter table tse
    rename column tse_name to name;
alter table tse
    rename column tse_status to status;
alter table tse
    rename column tse_serial to serial;
alter table tse
    alter column serial set not null;
alter table tse
    rename column tse_hashalgo to hashalgo;
alter table tse
    rename column tse_time_format to time_format;
alter table tse
    rename column tse_public_key to public_key;
alter table tse
    rename column tse_certificate to certificate;
alter table tse
    rename column tse_process_data_encoding to process_data_encoding;

-- this migration introduces tree structures for all records

-- one tree node, references exactly one parent
create table if not exists node (
    id bigint primary key generated always as identity (start with 1000),
    parent bigint not null references node(id),

    name text not null,
    description text not null default '',
    -- generated by trigger, will never be null, we cannot constrain this to be not null directly as not null constraints are checked before triggers
    path text,
    -- generated by trigger, will never be null, we cannot constrain this to be not null directly as not null constraints are checked before triggers
    parent_ids bigint[]
);

create index on node (parent);

-- create default nodes, we can use a bulk insert here as no trigger has yet been loaded,
-- which also means we need to manually compute the parent ids and path
insert into node (
    id, parent, name, parent_ids, path
) overriding system value
values
    (0, 0, '', '{0}', '/0'),
    (1, 0, 'event', '{0}', '/0/1')
    on conflict do nothing;

-- add the node column to all elements in the tree, and reference the 'event' node.
alter table account add column node_id bigint not null references node(id) default 1;
alter table account alter column node_id drop default;

alter table bon add column node_id bigint not null references node(id) default 1;
alter table bon alter column node_id drop default;

alter table cash_register add column node_id bigint not null references node(id) default 1;
alter table cash_register alter column node_id drop default;

alter table cash_register_stocking add column node_id bigint not null references node(id) default 1;
alter table cash_register_stocking alter column node_id drop default;

-- probably not needed since cashier shift always references a cashier which is inside the tree
-- alter table cashier_shift add column node_id bigint not null references node(id) default 1;
-- alter table cashier_shift alter column node_id drop default;

alter table config add column node_id bigint not null references node(id) default 1;
alter table config alter column node_id drop default;

-- probably not needed since it references a customer_account which is inside the tree
-- alter table customer_info add column node_id bigint not null references node(id) default 1;
-- alter table customer_info alter column node_id drop default;

alter table payout_run add column node_id bigint not null references node(id) default 1;
alter table payout_run alter column node_id drop default;

alter table product add column node_id bigint not null references node(id) default 1;
alter table product alter column node_id drop default;

alter table restriction_type add column node_id bigint not null references node(id) default 1;
alter table restriction_type alter column node_id drop default;

alter table tax add column node_id bigint not null references node(id) default 1;
alter table tax alter column node_id drop default;

alter table ticket add column node_id bigint not null references node(id) default 1;
alter table ticket alter column node_id drop default;

alter table till add column node_id bigint not null references node(id) default 1;
alter table till alter column node_id drop default;

alter table till_button add column node_id bigint not null references node(id) default 1;
alter table till_button alter column node_id drop default;

alter table till_layout add column node_id bigint not null references node(id) default 1;
alter table till_layout alter column node_id drop default;

alter table till_profile add column node_id bigint not null references node(id) default 1;
alter table till_profile alter column node_id drop default;

alter table tse add column node_id bigint not null references node(id) default 1;
alter table tse alter column node_id drop default;

alter table user_role add column node_id bigint not null references node(id) default 1;
alter table user_role alter column node_id drop default;

alter table user_tag add column node_id bigint not null references node(id) default 1;
alter table user_tag alter column node_id drop default;

alter table user_tag_secret add column node_id bigint not null references node(id) default 1;
alter table user_tag_secret alter column node_id drop default;

alter table usr add column node_id bigint not null references node(id) default 1;
alter table usr alter column node_id drop default;


-- TODO assign the associated event node to: ordr, transaction, line_item
-- TODO store the next id for orders in an event to increment them continuously
-- TODO: where do we put the hard coded products????????
